project_id = "ebonmrtmfopohayxfvdy"

[functions.amocrm-webhook-callback]
verify_jwt = false

[functions.create-amocrm-lead]
verify_jwt = false

[functions.amocrm-oauth-callback]
verify_jwt = false

[functions.bitrix-install]
verify_jwt = false

[functions.bitrix-app]
verify_jwt = false
