// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owilwkmenbrcinfwuvyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93aWx3a21lbmJyY2luZnd1dnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODMwNDEsImV4cCI6MjA2NjI1OTA0MX0.EOG3g98Q1YgZr76lodqziSfaRbY-4umnQtzaRxDzEFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);